### ISSUE TITLE
[BUG] [grid-motion-overlaps-with-navbar]

### ISSUE THREAD

**Issue by mananpatel06** [DavidHDev/react-bits#4]
**Bug Description**
Grid motion from backgrounds component overlaps with the navbar. (z-index issue)

**Steps To Reproduce**
Here's how you can reproduce the behavior described above:
1) Visit https://www.reactbits.dev/backgrounds/grid-motion
2) Scroll down the page

**Expected behavior**
Component should not overlap with the navbar.

**Screenshots**
![image](https://github.com/user-attachments/assets/08aec5f7-0cb4-4f0d-9213-a33cd7992385)

![image](https://github.com/user-attachments/assets/54e686bc-f2dc-4488-a5b7-658bc26036f2)

**Device (please complete the following information):**
 - Device: [Desktop]
 - Browser [Chrome, Brave]
 - Other: [All Tablet devices]

**Comment by DavidHDev** [comment]
Good find @mananpatel06 !

Feel free to open a PR if you find a fix!
