### ISSUE TITLE
[FEAT] [From this time to afterwards, developers first choice is tailwind not plain css, so change tabs, first tailwind then Default css]

### ISSUE THREAD

**Issue by sujal12344** [DavidHDev/react-bits#9]
**Description**
when developer come at for the components, then developers first choice is tailwind not plain css

![WhatsApp Image 2024-12-30 at 14 15 16_d603aa5b](https://github.com/user-attachments/assets/bc739a19-d2b6-48e8-a964-6a001fcdd1f6)

**Proposal**
Interchange above tabs

**Comment by sujal12344** [comment]
@DavidHDev Also for typescript first

**Comment by sujal12344** [comment]
@DavidHDev is typescript necessary or not? because its component only, copy paste

**Comment by DavidHDev** [comment]
That's simply not true, closing this issue.
